<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="**/*.tlg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="**/*.cmd" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
