<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>TinyLanguage.Interpreter</RootNamespace>
    <AssemblyName>TinyLanguage.Interpreter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TinyLanguage.Lexer\TinyLanguage.Lexer.csproj" />
  </ItemGroup>
</Project>
